"""add show_early_warning to organization

Revision ID: 05f5eaeeb51f
Revises: cef4ba69869a
Create Date: 2026-07-03 12:28:44.592090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05f5eaeeb51f'
down_revision = 'cef4ba69869a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.add_column(sa.Column('show_early_warning', sa.Boolean(), server_default='1', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.drop_column('show_early_warning')

    # ### end Alembic commands ###
