"""add absence table

Revision ID: 06b0916c4f09
Revises: f43af5914e2d
Create Date: 2026-05-19 09:38:55.194853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06b0916c4f09'
down_revision = 'f43af5914e2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('absence',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('ssid', sa.String(length=20), nullable=True),
    sa.Column('grade', sa.String(length=5), nullable=True),
    sa.Column('abs_desc', sa.String(length=200), nullable=True),
    sa.Column('abs_abbr', sa.String(length=20), nullable=True),
    sa.Column('bell_period', sa.String(length=20), nullable=True),
    sa.Column('school_yr', sa.String(length=9), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], ['site.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('absence')
    # ### end Alembic commands ###
