"""remove abs_abbr from absence

Revision ID: 081b8691319a
Revises: f9580ff14a57
Create Date: 2026-07-24 09:58:06.447431

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '081b8691319a'
down_revision = 'f9580ff14a57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('absence', schema=None) as batch_op:
        batch_op.drop_column('abs_abbr')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('absence', schema=None) as batch_op:
        batch_op.add_column(sa.Column('abs_abbr', mysql.VARCHAR(length=20), nullable=True))

    # ### end Alembic commands ###
