"""add max_students to course

Revision ID: 0d4f10ac6c66
Revises: 39c77f21881b
Create Date: 2026-05-24 17:17:17.065327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d4f10ac6c66'
down_revision = '39c77f21881b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_students', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.drop_column('max_students')

    # ### end Alembic commands ###
