"""add start_date and leave_date to student_course

Revision ID: 214848d8fd03
Revises: 081b8691319a
Create Date: 2026-07-26 00:33:05.020625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '214848d8fd03'
down_revision = '081b8691319a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('leave_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_course', schema=None) as batch_op:
        batch_op.drop_column('leave_date')
        batch_op.drop_column('start_date')

    # ### end Alembic commands ###
