"""add incident table

Revision ID: 39c77f21881b
Revises: 4c87acf472ec
Create Date: 2026-05-21 19:30:48.001167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39c77f21881b'
down_revision = '4c87acf472ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incident',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sisid', sa.String(length=20), nullable=True),
    sa.Column('site', sa.String(length=100), nullable=True),
    sa.Column('cds_code', sa.String(length=14), nullable=True),
    sa.Column('incident_id', sa.String(length=30), nullable=True),
    sa.Column('incident_date', sa.Date(), nullable=True),
    sa.Column('schoolyr', sa.String(length=9), nullable=True),
    sa.Column('incident_time', sa.String(length=10), nullable=True),
    sa.Column('day_of_week', sa.String(length=10), nullable=True),
    sa.Column('major', sa.String(length=100), nullable=True),
    sa.Column('minor', sa.String(length=100), nullable=True),
    sa.Column('suspended_days', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('incident')
    # ### end Alembic commands ###
