"""add composite school_yr+ssid index on Absence

Revision ID: 42cffa2f0111
Revises: 5f3cd110fda5
Create Date: 2026-07-30 11:14:05.794412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42cffa2f0111'
down_revision = '5f3cd110fda5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('absence', schema=None) as batch_op:
        batch_op.create_index('ix_absence_schoolyr_ssid', ['school_yr', 'ssid'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('absence', schema=None) as batch_op:
        batch_op.drop_index('ix_absence_schoolyr_ssid')

    # ### end Alembic commands ###
