"""add abs_date to absence

Revision ID: 4c87acf472ec
Revises: 06b0916c4f09
Create Date: 2026-05-19 10:04:35.855747

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c87acf472ec'
down_revision = '06b0916c4f09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('absence', schema=None) as batch_op:
        batch_op.add_column(sa.Column('abs_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('absence', schema=None) as batch_op:
        batch_op.drop_column('abs_date')

    # ### end Alembic commands ###
