"""add school year calendar fields to organization

Revision ID: 5baad1cec898
Revises: 05f5eaeeb51f
Create Date: 2026-07-18 22:29:18.345097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5baad1cec898'
down_revision = '05f5eaeeb51f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_school_year', sa.String(length=9), nullable=True))
        batch_op.add_column(sa.Column('first_school_day', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('last_school_day', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.drop_column('last_school_day')
        batch_op.drop_column('first_school_day')
        batch_op.drop_column('current_school_year')

    # ### end Alembic commands ###
