"""add performance indexes on Absence, Student.ssid, student_course

Revision ID: 5f3cd110fda5
Revises: e4f5a6b7c8d9
Create Date: 2026-07-30 11:11:02.792479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f3cd110fda5'
down_revision = 'e4f5a6b7c8d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('absence', schema=None) as batch_op:
        batch_op.create_index('ix_absence_schoolyr_site', ['school_yr', 'site_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_absence_ssid'), ['ssid'], unique=False)

    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_student_ssid'), ['ssid'], unique=False)

    with op.batch_alter_table('student_course', schema=None) as batch_op:
        batch_op.create_index('ix_student_course_course_leave', ['course_id', 'leave_date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_course', schema=None) as batch_op:
        batch_op.drop_index('ix_student_course_course_leave')

    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_student_ssid'))

    with op.batch_alter_table('absence', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_absence_ssid'))
        batch_op.drop_index('ix_absence_schoolyr_site')

    # ### end Alembic commands ###
