"""student_id per school year composite unique

Revision ID: 60d1641e7434
Revises: 5baad1cec898
Create Date: 2026-07-19 07:00:06.530146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60d1641e7434'
down_revision = '5baad1cec898'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('student_id'))
        batch_op.create_unique_constraint('uq_student_schoolyr', ['student_id', 'schoolyr'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_constraint('uq_student_schoolyr', type_='unique')
        batch_op.create_index(batch_op.f('student_id'), ['student_id'], unique=True)

    # ### end Alembic commands ###
