"""remove pk_yr_id from student

Revision ID: 65e8fa158dd2
Revises: 60d1641e7434
Create Date: 2026-07-21 11:22:18.416105

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '65e8fa158dd2'
down_revision = '60d1641e7434'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_column('pk_yr_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pk_yr_id', mysql.VARCHAR(length=20), nullable=True))

    # ### end Alembic commands ###
