"""add grad_auto_calculate_credits to organization

Revision ID: 71c642cf6723
Revises: b6e99f9d8304
Create Date: 2026-07-27 19:20:23.412592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71c642cf6723'
down_revision = 'b6e99f9d8304'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grad_auto_calculate_credits', sa.Boolean(), server_default='1', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.drop_column('grad_auto_calculate_credits')

    # ### end Alembic commands ###
