"""add student exit_date

Revision ID: 837d19ec0cea
Revises: 8bc952d5fc0f
Create Date: 2026-05-12 11:22:09.259570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '837d19ec0cea'
down_revision = '8bc952d5fc0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('exit_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_column('exit_date')

    # ### end Alembic commands ###
