"""add student demographic fields

Revision ID: 8bc952d5fc0f
Revises: 1efc1cedbfcd
Create Date: 2026-05-11 15:45:34.909078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bc952d5fc0f'
down_revision = '1efc1cedbfcd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ssid', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('cds_code', sa.String(length=14), nullable=True))
        batch_op.add_column(sa.Column('gender', sa.String(length=1), nullable=True))
        batch_op.add_column(sa.Column('gradyr', sa.String(length=4), nullable=True))
        batch_op.add_column(sa.Column('ethnicity', sa.String(length=3), nullable=True))
        batch_op.add_column(sa.Column('frm_code', sa.String(length=1), nullable=True))
        batch_op.add_column(sa.Column('english_status', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('enter_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('disability', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('sped_exdate', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('dwelling', sa.String(length=2), nullable=True))
        batch_op.add_column(sa.Column('migrant', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('schoolyr', sa.String(length=9), nullable=True))
        batch_op.add_column(sa.Column('foster', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('sed504', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('pk_yr_id', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_column('pk_yr_id')
        batch_op.drop_column('sed504')
        batch_op.drop_column('foster')
        batch_op.drop_column('schoolyr')
        batch_op.drop_column('migrant')
        batch_op.drop_column('dwelling')
        batch_op.drop_column('sped_exdate')
        batch_op.drop_column('disability')
        batch_op.drop_column('enter_date')
        batch_op.drop_column('english_status')
        batch_op.drop_column('frm_code')
        batch_op.drop_column('ethnicity')
        batch_op.drop_column('gradyr')
        batch_op.drop_column('gender')
        batch_op.drop_column('cds_code')
        batch_op.drop_column('ssid')

    # ### end Alembic commands ###
