"""add graduation status settings to organization

Revision ID: a1b2c3d4e5f6
Revises: e3c642e04e41
Create Date: 2026-07-27 09:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1b2c3d4e5f6'
down_revision = 'e3c642e04e41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.add_column(sa.Column('show_graduation', sa.Boolean(), server_default='1', nullable=False))
        batch_op.add_column(sa.Column('grad_credits_required', sa.Integer(), server_default='220', nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.drop_column('grad_credits_required')
        batch_op.drop_column('show_graduation')

    # ### end Alembic commands ###
