"""add graduation_requirement table

Revision ID: b6e99f9d8304
Revises: a1b2c3d4e5f6
Create Date: 2026-07-27 19:04:03.137167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6e99f9d8304'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('graduation_requirement',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('subject_name', sa.String(length=100), nullable=False),
    sa.Column('credits_required', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('departments', sa.Text(), nullable=True),
    sa.Column('name_keywords', sa.Text(), nullable=True),
    sa.Column('name_exclude_keywords', sa.Text(), nullable=True),
    sa.Column('is_catch_all', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subject_name')
    )
    # ### end Alembic commands ###

    # Seed the subject-area breakdown that was previously hardcoded in routes.py,
    # so the Graduation tab keeps behaving the same after this upgrade.
    grad_req = sa.table('graduation_requirement',
        sa.column('subject_name', sa.String),
        sa.column('credits_required', sa.Numeric),
        sa.column('departments', sa.Text),
        sa.column('name_keywords', sa.Text),
        sa.column('name_exclude_keywords', sa.Text),
        sa.column('is_catch_all', sa.Boolean),
        sa.column('sort_order', sa.Integer),
    )
    op.bulk_insert(grad_req, [
        {'subject_name': 'English', 'credits_required': 40, 'departments': 'English',
         'name_keywords': None, 'name_exclude_keywords': None, 'is_catch_all': False, 'sort_order': 0},
        {'subject_name': 'VPA/Foreign Language', 'credits_required': 10,
         'departments': 'Foreign Language,Art,Music',
         'name_keywords': None, 'name_exclude_keywords': None, 'is_catch_all': False, 'sort_order': 1},
        {'subject_name': 'Algebra I', 'credits_required': 10, 'departments': 'Mathematics',
         'name_keywords': 'ALGEBRA I', 'name_exclude_keywords': 'ALGEBRA II', 'is_catch_all': False, 'sort_order': 2},
        {'subject_name': 'Mathematics', 'credits_required': 20, 'departments': 'Mathematics',
         'name_keywords': None, 'name_exclude_keywords': None, 'is_catch_all': False, 'sort_order': 3},
        {'subject_name': 'Physical Education', 'credits_required': 20, 'departments': 'Physical Education',
         'name_keywords': None, 'name_exclude_keywords': None, 'is_catch_all': False, 'sort_order': 4},
        {'subject_name': 'Life Science', 'credits_required': 10, 'departments': 'Life Science',
         'name_keywords': None, 'name_exclude_keywords': None, 'is_catch_all': False, 'sort_order': 5},
        {'subject_name': 'Physical Science', 'credits_required': 10, 'departments': 'Physical Science',
         'name_keywords': None, 'name_exclude_keywords': None, 'is_catch_all': False, 'sort_order': 6},
        {'subject_name': 'Social Science', 'credits_required': 30, 'departments': 'Social Science',
         'name_keywords': None, 'name_exclude_keywords': None, 'is_catch_all': False, 'sort_order': 7},
        {'subject_name': 'Electives', 'credits_required': 65, 'departments': None,
         'name_keywords': None, 'name_exclude_keywords': None, 'is_catch_all': True, 'sort_order': 8},
        {'subject_name': 'CTE', 'credits_required': 5, 'departments': 'Industrial Arts/Vocational Education',
         'name_keywords': None, 'name_exclude_keywords': None, 'is_catch_all': False, 'sort_order': 9},
    ])


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('graduation_requirement')
    # ### end Alembic commands ###
