"""extend course model for bulk section import

Revision ID: ba4fa089337b
Revises: d30ea64f4e89
Create Date: 2026-07-22 12:01:27.123715

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ba4fa089337b'
down_revision = 'd30ea64f4e89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('section_id', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('course_catalog_id', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('college_dept', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('department', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('credits', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('term_code', sa.String(length=10), nullable=True))
        batch_op.alter_column('course_code',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
        batch_op.drop_index(batch_op.f('course_code'))
        batch_op.create_unique_constraint('uq_course_site_section', ['site_id', 'section_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.drop_constraint('uq_course_site_section', type_='unique')
        batch_op.create_index(batch_op.f('course_code'), ['course_code'], unique=True)
        batch_op.alter_column('course_code',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
        batch_op.drop_column('term_code')
        batch_op.drop_column('credits')
        batch_op.drop_column('department')
        batch_op.drop_column('college_dept')
        batch_op.drop_column('course_catalog_id')
        batch_op.drop_column('section_id')

    # ### end Alembic commands ###
