"""add dashboard card visibility to organization

Revision ID: ba71dd8f782b
Revises: 0d4f10ac6c66
Create Date: 2026-05-25 20:19:25.229732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba71dd8f782b'
down_revision = '0d4f10ac6c66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.add_column(sa.Column('show_demographics', sa.Boolean(), server_default='1', nullable=False))
        batch_op.add_column(sa.Column('show_absenteeism', sa.Boolean(), server_default='1', nullable=False))
        batch_op.add_column(sa.Column('show_discipline', sa.Boolean(), server_default='1', nullable=False))
        batch_op.add_column(sa.Column('show_swd', sa.Boolean(), server_default='1', nullable=False))
        batch_op.add_column(sa.Column('show_registration', sa.Boolean(), server_default='1', nullable=False))
        batch_op.add_column(sa.Column('show_enrollment', sa.Boolean(), server_default='1', nullable=False))
        batch_op.add_column(sa.Column('show_attendance_rates', sa.Boolean(), server_default='1', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.drop_column('show_attendance_rates')
        batch_op.drop_column('show_enrollment')
        batch_op.drop_column('show_registration')
        batch_op.drop_column('show_swd')
        batch_op.drop_column('show_discipline')
        batch_op.drop_column('show_absenteeism')
        batch_op.drop_column('show_demographics')

    # ### end Alembic commands ###
