"""add student_subject_credits table

Revision ID: c7d8e9f0a1b2
Revises: 603bd9071af8
Create Date: 2026-07-28 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7d8e9f0a1b2'
down_revision = '603bd9071af8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_subject_credits',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('student_id', sa.String(length=50), nullable=False),
        sa.Column('subject_name', sa.String(length=100), nullable=False),
        sa.Column('credits', sa.Numeric(precision=8, scale=2), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('student_id', 'subject_name', name='uq_student_subject')
    )
    with op.batch_alter_table('student_subject_credits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_student_subject_credits_student_id'), ['student_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_subject_credits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_student_subject_credits_student_id'))

    op.drop_table('student_subject_credits')
    # ### end Alembic commands ###
