"""add grade table

Revision ID: cef4ba69869a
Revises: ba71dd8f782b
Create Date: 2026-05-26 07:35:53.762137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cef4ba69869a'
down_revision = 'ba71dd8f782b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grade',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('grades_stuid', sa.String(length=50), nullable=False),
    sa.Column('grades_schoolid', sa.String(length=100), nullable=True),
    sa.Column('grades_coursenum', sa.String(length=50), nullable=True),
    sa.Column('grades_teacherid', sa.String(length=50), nullable=True),
    sa.Column('grades_courseyr', sa.String(length=20), nullable=True),
    sa.Column('grades_term', sa.String(length=20), nullable=True),
    sa.Column('grades_grade', sa.String(length=5), nullable=True),
    sa.Column('grades_mark', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('grades_type', sa.String(length=20), nullable=True),
    sa.Column('grades_credatt', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('grades_credcomp', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('grades_currgrade', sa.String(length=5), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('grade', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_grade_grades_stuid'), ['grades_stuid'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grade', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_grade_grades_stuid'))

    op.drop_table('grade')
    # ### end Alembic commands ###
