"""add city, state, zip, and principal fields to site

Revision ID: d30ea64f4e89
Revises: 65e8fa158dd2
Create Date: 2026-07-22 10:00:20.225900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd30ea64f4e89'
down_revision = '65e8fa158dd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('site', schema=None) as batch_op:
        batch_op.add_column(sa.Column('site_city', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('site_state', sa.String(length=2), nullable=True))
        batch_op.add_column(sa.Column('site_zip', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('principal_first_name', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('principal_last_name', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('principal_email', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('principal_phone', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('site', schema=None) as batch_op:
        batch_op.drop_column('principal_phone')
        batch_op.drop_column('principal_email')
        batch_op.drop_column('principal_last_name')
        batch_op.drop_column('principal_first_name')
        batch_op.drop_column('site_zip')
        batch_op.drop_column('site_state')
        batch_op.drop_column('site_city')

    # ### end Alembic commands ###
