"""add continuation graduation track support

Revision ID: d94329389d8b
Revises: d98a0248b96b
Create Date: 2026-09-21 15:28:45.440093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd94329389d8b'
down_revision = 'd98a0248b96b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('graduation_requirement', schema=None) as batch_op:
        batch_op.add_column(sa.Column('credits_required_continuation', sa.Numeric(precision=6, scale=2), nullable=True))

    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grad_credits_required_continuation', sa.Integer(), nullable=True))

    with op.batch_alter_table('site', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grad_track', sa.String(length=20), server_default='standard', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('site', schema=None) as batch_op:
        batch_op.drop_column('grad_track')

    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.drop_column('grad_credits_required_continuation')

    with op.batch_alter_table('graduation_requirement', schema=None) as batch_op:
        batch_op.drop_column('credits_required_continuation')

    # ### end Alembic commands ###
