"""add show_calpads to organization

Revision ID: e3c642e04e41
Revises: 214848d8fd03
Create Date: 2026-07-26 08:59:26.272823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3c642e04e41'
down_revision = '214848d8fd03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.add_column(sa.Column('show_calpads', sa.Boolean(), server_default='1', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.drop_column('show_calpads')

    # ### end Alembic commands ###
