"""widen parent relationship column

Revision ID: f9580ff14a57
Revises: 5e72cc9c770e
Create Date: 2026-07-23 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9580ff14a57'
down_revision = '5e72cc9c770e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parent', schema=None) as batch_op:
        batch_op.alter_column('relationship',
               existing_type=sa.String(length=30),
               type_=sa.String(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parent', schema=None) as batch_op:
        batch_op.alter_column('relationship',
               existing_type=sa.String(length=50),
               type_=sa.String(length=30),
               existing_nullable=False)

    # ### end Alembic commands ###
